# Generated by Django 5.1.5 on 2025-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=40, null=True),
        ),
    ]
