# Generated by Django 5.1.5 on 2025-01-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=40)),
                ('Transaction_type', models.CharField(choices=[('succesfull', 'Succesfull'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=40)),
                ('status', models.CharField(choices=[('succesfull', 'Succesfull'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.accountmodel')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.accountmodel')),
            ],
        ),
    ]
