# Generated by Django 5.1.5 on 2025-02-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_account_number'),
        ('transactions', '0003_alter_transactionsmodel_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='receiver',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.accountmodel'),
        ),
    ]
