# Generated by Django 5.1.5 on 2025-02-20 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactionsmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
