# Generated by Django 5.1.5 on 2025-01-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='Transaction_type',
        ),
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='sender_account',
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.accountmodel'),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.accountmodel'),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], default='transfer', max_length=40),
        ),
    ]
